import GlobalState from "@/context";
import "./globals.css";

import Sidebar from "@/components/sidebar/page";
import Header from "@/components/header/page";
import NextAuthProvider from "@/auth_provider";

export const metadata = {
  title: "GGroselle DashBoard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <NextAuthProvider>
          <GlobalState>
            <div className="flex h-screen overflow-hidden bg-white">
              <Sidebar />

              <div className="relative flex flex-1 flex-col overflow-y-auto overflow-hidden">
                <Header />
                <div>{children}</div>
              </div>
            </div>
          </GlobalState>
        </NextAuthProvider>
      </body>
    </html>
  );
}
